### ISSUE TITLE
problems receiving a video call

### ISSUE THREAD

**Issue by fleexcl** [NNakreSS/VideoCall#1]
I have a problem, when I receive a video call from another player, the phone automatically hides and I can't keep seeing the cell phone screen, then when the call ends, my player stays with the mouse on the screen and I can't take out the phone. this problem only happens to the person receiving the call, while the caller has no problems, any idea what it could be?

https://streamable.com/l6dwcl

**Comment by NNakreSS** [comment]
As I mentioned in the script, you should not install the nakres_videocall
script all the codes are placed in qb-phone

vSuk ***@***.***>, 22 Şub 2022 Sal, 08:05 tarihinde şunu
yazdı:

**Comment by ElvisMatias** [comment]
intends to download the qb-phone you have to use it on my server, will everything work fine?
