### ISSUE TITLE
Cancel Call Option not Working !

### ISSUE THREAD

**Issue by nagavalliop9** [NNakreSS/VideoCall#2]
Not able to cancel an on-going call. 
Outgoing call can be cancelled.

![image](https://user-images.githubusercontent.com/97756782/156876443-21eb36a3-f148-4a12-8c4f-6c36d223c747.png)

**Comment by NNakreSS** [comment]
Check the clability of the button , Check that the button is clicked; if you are unable to perform an operation, you can solve the problem by increasing the z-index value of the button.
